export default [
    {
      volume: 'Vol. 1',
      author: 'Kimbal, C.P.',
      title: 'Lepidoptera of Florida',
      year: '1965',
      image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1965_001.png',
      pdf: 'https://drive.google.com/file/d/1umIctT5WaspLgPzpfgtwHUNEIoARd1Rs/view?usp=sharing',
    },
    {
        volume: 'Vol. 2',
        author: 'McCrone, J.D. & Stone, K.J.',
        title: 'The Widow Spider of Florida',
        year: '1965',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1965_002.png',
        pdf: 'https://drive.google.com/file/d/1eLUqjj36NOjygbaRnk62nuM-E94xhhFz/view?usp=sharing',
      },
      {
        volume: 'Vol. 3',
        author: 'Deckle, G.W.',
        title: 'The Armored Scale Insects',
        year: '1965, revised 1976',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1965_003.png',
        pdf: 'https://drive.google.com/file/d/1Lxb_yRNqhW1PatbelocrZjsUL7h4InWV/view?usp=sharing',
      },
      {
        volume: 'Vol. 4',
        author: 'Muma, M.H',
        title: 'Scorpions, Whip Scorpions, and Wind Scorpions of Florida',
        year: '1967',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1967_004.png',
        pdf: 'https://drive.google.com/file/d/1aumGE2Rs1oYIS0AN9WmoGKo9VB9iGyM9/view?usp=sharing',
      },
      {
        volume: 'Vol. 5',
        author: 'Muma, M.H',
        title: 'Synoptic Review of North American, Central American and West Indian Solpugida',
        year: '1970',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1970_005.png',
        pdf: 'https://drive.google.com/file/d/1KWglSO197ecmO4OAg1W1Lsr84Y7dG5dG/view?usp=sharing',
      },
      {
        volume: 'Vol. 6',
        author: 'Muma, M.H. & Denmark, H.A.',
        title: 'Phytoseiidae of Florida',
        year: '1970',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1970_006.png',
        pdf: 'https://drive.google.com/file/d/1uLvAB8gaGSlufPY7rBrXXQaX8c3qE2UY/view?usp=sharing',
      },
      {
        volume: 'Vol. 7',
        author: 'Spencer, K.A.',
        title: 'Agromyzidae of Florida',
        year: '1973',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1973_007.png',
        pdf: 'https://drive.google.com/file/d/1Et02j0YQ7TWW3uhl0SJiA3K9SWR4d9qB/view?usp=sharing',
      },
      {
        volume: 'Vol. 8',
        author: 'Woodruff, R.E.',
        title: 'Scarab Beetles of Florida, Part. I, The Laparosticti',
        year: '1973',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1973_008.png',
        pdf: 'https://drive.google.com/file/d/19h8tFpDaq-fNwMRg52LwhfN1w9ytgoGB/view?usp=sharing',
      },
      {
        volume: 'Vol. 9',
        author: 'Heinrich, G.H.',
        title: 'Ichneumoninae of Florida and Neighboring States',
        year: '1977',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1977_009.png',
        pdf: 'https://drive.google.com/file/d/1dKxGc5sAknsq9lfuPSOrFQ71nKgQcyZi/view?usp=sharing',
      },
      {
        volume: 'Vol. 10',
        author: 'Blanton, F.S.',
        title: 'Sand Flies of Florida',
        year: '1979',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1979_010.png',
        pdf: 'https://drive.google.com/file/d/13TkoOc9qoQPLQcEu5N7voIRMDDS5tehE/view?usp=sharing',
      },
      {
        volume: 'Vol. 11',
        author: 'Hamon, A.B. & Williams, M.L.',
        title: 'Soft Scale Insects of Florida',
        year: '1984',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1984_011.png',
        pdf: 'https://drive.google.com/file/d/13P5VROw78mGwZzTyp-6xtSBGpKtaU06g/view?usp=sharing',
      },
      {
        volume: 'Vol. 12',
        author: 'Baranowski, R.M. & Slater, J.A.',
        title: 'Coreidae of Florida',
        year: '1986',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1986_012.png',
        pdf: 'https://drive.google.com/file/d/1ChY1djxNtFuu1CckcCYA2hTkdOBu2Ota/view?usp=sharing',
      },
      {
        volume: 'Vol. 13',
        author: 'Woodruff, R.E. & Beck, B.M.',
        title: 'Scarab Beetles of Florida, Part II, May or June Beetles (Genus Phyllophaga)',
        year: '1989',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1989_013.png',
        pdf: 'https://drive.google.com/file/d/1ySK-ZbggeiZQoCx0tjUAGHPLeVTSUIA7/view?usp=sharing',
      },
      {
        volume: 'Vol. 14',
        author: 'Slater, J.A. & Baranowski, R.M.',
        title: 'Lygaeidae of Florida (Hemiptera: Heteroptera)',
        year: '1990',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1990_014.png',
        pdf: 'https://drive.google.com/file/d/1NkN0RIfuZQWS2g-0HtsFpfx3k5RuiAHO/view?usp=sharing',
      },
      {
        volume: 'Vol. 15',
        author: 'Thomas, M.C.',
        title: 'The Flat Bark Beetles of Florida',
        year: '1993',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1993_015.png',
        pdf: 'https://drive.google.com/file/d/1TPb9SwAz4cw0RZqWcHf-FAZqKt3ZYv9O/view?usp=sharing',
      },
      {
        volume: 'Vol. 16',
        author: 'Peck, S.B. & Thomas, M.C.',
        title: 'A Distributional Checklist of the Beetles (Coleoptera) of Florida',
        year: '1998',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_1998_016.png',
        pdf: 'https://drive.google.com/file/d/1mUywdpsl3k9y6-JXU5xBsMb_VNLLruh9/view?usp=sharing',
      },
      {
        volume: 'Vol. 17',
        author: 'Heppner, J.B.',
        title: 'Lepidoptera of Florida. Part 1. Introduction and Catalog',
        year: 'released 2003, printed 2007',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_2003_017.png',
        pdf: 'https://drive.google.com/file/d/1i9qBoKDw4h6Lc6pC2O49LbnbOQOSoIoW/view?usp=sharing',
      },
      {
        volume: 'Vol. 18',
        author: 'Peck, S.B.',
        title: 'A Checklist of the Beetles of Cuba with Data on Distributions and Bionomics (Insecta Coleoptera)',
        year: '2005',
        image: '/images/otherpubs/FSCA_Arthropods/AFNLA_2005_018.jpg',
        pdf: 'https://drive.google.com/file/d/1QoSHGmuEvIW2hT7Bcb70G8HEb9TI9Gco/view?usp=sharing',
      },
  ]  
    