export default [
    {
      volume: 'Vol. 1',
      author: 'Frank, J.H.',
      title: 'A Revision of the New World Species of the Genus <i>Neobisnius</i> Ganglbauer (Coleoptera: Staphylinidae)',
      year: '1981',
      image: '/images/otherpubs/FSCA_Occasional/OPFSCA_1981_001.png',
      pdf: '/PDF/2024_DorisLagos.pdf',
    },
    {
        volume: 'Vol. 2',
        author: 'Young, Jr., F.N.',
        title: 'Predacious Water Beetles of the Genus <i>Desmopachria</i>: The Convexa-grana Group (Coleoptera: Dytiscidae)',
        year: '1981',
        image: '/images/otherpubs/FSCA_Occasional/OPFSCA_1981_002.png',
        pdf: '/PDF/2024_DorisLagos.pdf',
      },
      {
        volume: 'Vol. 3',
        author: 'Thomas, M.C.',
        title: 'A Revision of the New World Species of <i>Placonotus</i> Macleay (Coleoptera: Cucujidae: Laemophloeinae)',
        year: '1984',
        image: '/images/otherpubs/FSCA_Occasional/OPFSCA_1984_003.png',
        pdf: '/PDF/2024_DorisLagos.pdf',
      },
      {
        volume: 'Vol. 4',
        author: 'Denmark, H.A.',
        title: 'A Revision of the Genus <i>Amblyseius</i> Berlese, 1914 (Acari: Phytoseiidae)',
        year: '1989',
        image: '/images/otherpubs/FSCA_Occasional/OPFSCA_1989_004.png',
        pdf: '/PDF/2024_DorisLagos.pdf',
      },
      {
        volume: 'Vol. 5',
        author: 'Cokendolpher, J.C. & Camilo-Rivera, G.R.',
        title: 'Annotated Bibliography to the Harvestmen of the West Indies (Arachnida: Opiliones)',
        year: '1989',
        image: '/images/otherpubs/FSCA_Occasional/OPFSCA_1989_005.png',
        pdf: '/PDF/2024_DorisLagos.pdf',
      },
      {
        volume: 'Vol. 6',
        author: 'Stephan, K.H.',
        title: 'The Bothrideridae and Colydiidae of America north of Mexico (Coleoptera: Clavicornia and Heteromera)',
        year: '1989',
        image: '/images/otherpubs/FSCA_Occasional/OPFSCA_1989_006.png',
        pdf: '/PDF/2024_DorisLagos.pdf',
      },
      {
        volume: 'Vol. 7',
        author: 'Denmark, H.A.',
        title: 'A Revision of the Genus <i>Typhlodromus</i> Scheuten (Acari: Phytoseiidae)',
        year: '1992',
        image: '/images/otherpubs/FSCA_Occasional/OPFSCA_1992_007.png',
        pdf: '/PDF/2024_DorisLagos.pdf',
      },
      {
        volume: 'Vol. 8',
        author: 'Nguyen, R. & Sailer, R.I.',
        title: 'Catalog of Aleyrodidae on Citrus and their Natural Enemies (Homoptera-Aleyrodidae)',
        year: '1993',
        image: '/images/otherpubs/FSCA_Occasional/OPFSCA_1993_008.png',
        pdf: '/PDF/2024_DorisLagos.pdf',
      },
      {
        volume: 'Vol. 9',
        author: 'Skelley, P.E.',
        title: 'Revision of the Genus <i>Ischyrus</i> Lacordaire (1842) of North and Central America (Coleoptera: Erotylidae)',
        year: '1998',
        image: '/images/otherpubs/FSCA_Occasional/OPFSCA_1998_009.png',
        pdf: '/PDF/2024_DorisLagos.pdf',
      },
      {
        volume: 'Vol. 10',
        author: 'Galley, K.E.M.',
        title: 'Revision of the Genus <i>Selonodon</i> Latreille (Coleoptera: Cebrionidae)',
        year: '1999',
        image: '/images/otherpubs/FSCA_Occasional/OPFSCA_1999_010.png',
        pdf: '/PDF/2024_DorisLagos.pdf',
      },
      {
        volume: 'Vol. 11',
        author: 'Edwards, G.B.',
        title: 'Revision of the Jumping Spiders of the Genus Phidippus (Araneae: Salticidae)',
        year: '2004',
        image: '/images/otherpubs/FSCA_Occasional/OPFSCA_2004_011.png',
        pdf: '/PDF/2024_DorisLagos.pdf',
      },
      {
        volume: 'Vol. 12',
        author: 'Bright, D.E.',
        title: 'A Taxonomic Monograph of the Bark and Ambrosia Beetles of the West Indies (Coleoptera: Curculionoidea: Scolytidae)',
        year: '2019',
        image: '/images/otherpubs/FSCA_Occasional/OPFSCA_2019_012.jpg',
        pdf: '/PDF/2024_DorisLagos.pdf',
      },
      {
        volume: 'Vol. 13',
        author: 'Mathison, B.A.',
        title: 'Click Beetles (Coleoptera: Elateridae) of the Southeastern United States',
        year: '2021',
        image: '/images/otherpubs/FSCA_Occasional/OPFSCA_2021_013.jpg',
        pdf: '/PDF/2024_DorisLagos.pdf',
        pdfhigh: '/PDF/2024_DorisLagos.pdf',
      },
  ]
    