export default [
  {
    year: '2024',
    researcher: 'Lagos-Kutz, Doris',
    title: 'The genus <i>Aphis</i>',
    taxon: 'Aphididae (Hemiptera)',
    pdf: '/PDF/2024_DorisLagos.pdf',
  },
  {
    year: '2024',
    researcher: 'Milne, Mark',
    title: 'A taxonomic revision of the wetland-adapted dwarf spider genus, <i>Floricomus</i> (Araneae: Linyphiidae)',
    taxon: 'Linyphiidae (Araneae)',
    pdf: '/PDF/2024_MarcMilne.pdf',
  },
  {
    year: '2024',
    researcher: 'Solomon, Hendrix',
    title: 'Cixiid planthopper genus <i>Melanoliarus</i>',
    taxon: 'Cixiidae (Hemiptera)',
    pdf: '/PDF/2024_SolomonHendrix.pdf',
  },
  {
    year: '2023',
    researcher: 'Goff, Roy',
    title: 'Lepidoptera',
    taxon: 'Lepidoptera',
    pdf: '/PDF/2023_RoyGoff.pdf',
  },
  {
    year: '2023',
    researcher: 'Evans, Arthur <br> Ivanov, Kaloyan',
    title: 'Curation of unidentified Melolonthinae (Scarabaeidae) and Formicidae (Hymenoptera)',
    taxon: 'Scarabaeidae (Coleoptera) <br> Formicidae (Hymenoptera)',
    pdf: '/PDF/2023_EvansArt.pdf',
  },
  {
    year: '2023',
    researcher: 'Anderson, Robert',
    title: 'Curation of unidentified Curculionidae (Coleoptera), part 1',
    taxon: 'Curculionidae (Coleoptera)',
    pdf: '/PDF/2023_AndersonBob.pdf',
  },
  {
    year: '2022',
    researcher: 'Sutherland, Rachel',
    title: 'Color evolution in Erotylidae (Coleoptera)',
    taxon: 'Erotylidae (Coleoptera)',
    pdf: '/PDF/2022_SutherlandRachel.pdf',
  },
  {
    year: '2020',
    researcher: 'Ortiz-Acevedo, Elena',
    title: 'Exploring mimicry in Neotropical butterflies: a morphological and geographical approach',
    taxon: 'Nymphalidae (Lepidoptera)',
    pdf: '/PDF/2020_OrtizAcevedo.pdf',
  },
  {
    year: '2020',
    researcher: 'Orfinger, Alexander B.',
    title: 'Taxonomic Revision of <i>Polycentropus</i> (Trichoptera: Polycentropodidae) from the Eastern Nearctic',
    taxon: 'Polycentropodidae (Trichoptera)',
    pdf: '/PDF/2020_OrfingerAlex.pdf',
  },
  {
    year: '2019',
    researcher: ' Domínguez León, Daniel E.',
    title: 'Systematics of the genus <i>Oxacis</i> LeConte (Coleoptera: Oedemeridae)',
    taxon: 'Oedemeridae (Coleoptera)',
    pdf: '/PDF/2019_DominguezLeon.pdf',
  },
  {
    year: '2019',
    researcher: 'Sotto-Alviola, Marnelli P.',
    title: 'Springtails (Hexapoda: Collembola) collection, preservation, morphology, taxonomy and identification training',
    taxon: 'Collembola',
    pdf: '/PDF/2019_SottoAlviola.pdf',
  },
  {
    year: '2019',
    researcher: 'Ardila-Camacho, Adrian',
    title: 'Systematics of the mantidfly subfamily Symphrasinae (Neuroptera: Mantispidae)',
    taxon: 'Mantispidae (Neuroptera)',
    pdf: '/PDF/2019_ArdilaCamacho.pdf',
  },
  {
    year: '2018',
    researcher: 'Shirai, Leila T.',
    title: 'The contribution of the developmental hierarchy in morphological diversification',
    taxon: 'Nymphalidae (Lepidoptera) <br> Saturniidae (Lepidoptera)',
    pdf: '/PDF/2018_TerukoShirai.pdf',
  },
]
  