export default [
    {
    year: '2025',
    researcher: 'Przybylowicz, Luzasz',
    title: 'Untangling of the Arctiinae (Lepidoptera: Erebidae) diversity in the collection of the MGCL & FSCA – a hunt for new species',
    taxon: 'Arctiinae (Lepidoptera)',
    pdf: 'https://drive.google.com/file/d/1mLIySpf4UDBfuazTnZVL1TL61fno_J9O',
  },
  {
    year: '2024',
    researcher: 'Lagos-Kutz, Doris',
    title: 'The genus <i>Aphis</i>',
    taxon: 'Aphididae (Hemiptera)',
    pdf: 'https://drive.google.com/file/d/1DlWZeDcthGZdoi-5rbG6KLXojYOZKZrb/view?usp=sharing',
  },
  {
    year: '2024',
    researcher: 'Milne, Mark',
    title: 'A taxonomic revision of the wetland-adapted dwarf spider genus, <i>Floricomus</i> (Araneae: Linyphiidae)',
    taxon: 'Linyphiidae (Araneae)',
    pdf: 'https://drive.google.com/file/d/1p1BaxA9bnttGdpKANyJHrfPGDMEZG7-Y/view?usp=sharing',
  },
  {
    year: '2024',
    researcher: 'Solomon, Hendrix',
    title: 'Cixiid planthopper genus <i>Melanoliarus</i>',
    taxon: 'Cixiidae (Hemiptera)',
    pdf: 'https://drive.google.com/file/d/1GJ3-z9Qhgpo4U25dgzsAJubAan7m_Bku/view?usp=sharing',
  },
  {
    year: '2023',
    researcher: 'Goff, Roy',
    title: 'Lepidoptera',
    taxon: 'Lepidoptera',
    pdf: 'https://drive.google.com/file/d/1jWI1jQh_UlPwcyFF9UdQ8Ik5-bBbKEur/view?usp=sharing',
  },
  {
    year: '2023',
    researcher: 'Evans, Arthur <br> Ivanov, Kaloyan',
    title: 'Curation of unidentified Melolonthinae (Scarabaeidae) and Formicidae (Hymenoptera)',
    taxon: 'Scarabaeidae (Coleoptera) <br> Formicidae (Hymenoptera)',
    pdf: 'https://drive.google.com/file/d/1p3rouaVGdet4Wmn3brlDUgvEzN1bM2dP/view?usp=sharing',
  },
  {
    year: '2023',
    researcher: 'Anderson, Robert',
    title: 'Curation of unidentified Curculionidae (Coleoptera), part 1',
    taxon: 'Curculionidae (Coleoptera)',
    pdf: 'https://drive.google.com/file/d/1Mdn3cUajZRijL6h5EJVDsUHPVby01yLM/view?usp=sharing',
  },
  {
    year: '2022',
    researcher: 'Sutherland, Rachel',
    title: 'Color evolution in Erotylidae (Coleoptera)',
    taxon: 'Erotylidae (Coleoptera)',
    pdf: 'https://drive.google.com/file/d/1GXmFTGujMEd-2ioapWOpYygc0Rig1jZS/view?usp=sharing',
  },
  {
    year: '2020',
    researcher: 'Ortiz-Acevedo, Elena',
    title: 'Exploring mimicry in Neotropical butterflies: a morphological and geographical approach',
    taxon: 'Nymphalidae (Lepidoptera)',
    pdf: 'https://drive.google.com/file/d/1Wtu8mPZcZ27atIc8R9CYa79hhXRhx5qN/view?usp=sharing',
  },
  {
    year: '2020',
    researcher: 'Orfinger, Alexander B.',
    title: 'Taxonomic Revision of <i>Polycentropus</i> (Trichoptera: Polycentropodidae) from the Eastern Nearctic',
    taxon: 'Polycentropodidae (Trichoptera)',
    pdf: 'https://drive.google.com/file/d/19txfGJTCK4WUVYem1gaj9oIwJu-jusuU/view?usp=sharing',
  },
  {
    year: '2019',
    researcher: ' Domínguez León, Daniel E.',
    title: 'Systematics of the genus <i>Oxacis</i> LeConte (Coleoptera: Oedemeridae)',
    taxon: 'Oedemeridae (Coleoptera)',
    pdf: 'https://drive.google.com/file/d/1qbs3QvPBUMMNnXLN6fpkfmUFsNwtI2jK/view?usp=sharing',
  },
  {
    year: '2019',
    researcher: 'Sotto-Alviola, Marnelli P.',
    title: 'Springtails (Hexapoda: Collembola) collection, preservation, morphology, taxonomy and identification training',
    taxon: 'Collembola',
    pdf: 'https://drive.google.com/file/d/1da5A-PQ4xIwFARylvw3XrMBbzcNAgrwx/view?usp=sharing',
  },
  {
    year: '2019',
    researcher: 'Ardila-Camacho, Adrian',
    title: 'Systematics of the mantidfly subfamily Symphrasinae (Neuroptera: Mantispidae)',
    taxon: 'Mantispidae (Neuroptera)',
    pdf: 'https://drive.google.com/file/d/17rDh5wKp1AsuavW9KimMnhUb62xkijiQ/view?usp=sharing',
  },
  {
    year: '2018',
    researcher: 'Shirai, Leila T.',
    title: 'The contribution of the developmental hierarchy in morphological diversification',
    taxon: 'Nymphalidae (Lepidoptera) <br> Saturniidae (Lepidoptera)',
    pdf: 'https://drive.google.com/file/d/19K6CGyYIlV4RwUWBiY0Nplhswg1q6jxb/view?usp=sharing',
  },
]
  